openapi: 3.0.1
servers:
  - url: 'https://api.bcs.{env}.peterbean.net/cloudcdn/v1'
    variables:
      env:
        enum:
          - dev
          - prod
        default: dev
  - url: 'https://api.bcs.peterbean.net/cloudcdn/v1'
    description: default PROD env

info:
  description: >-
    CloudCdn API to create distributions.
  version: 1.0.0
  title: OpenAPI distribution info
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: distribution
    description: Everything about your distributions
paths:
  /distributions:
    post:
      tags:
        - distributions
      summary: Create new distribution
      description: ''
      operationId: createDistribution
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'schemas/distribution.yaml#/DistributionUpsert'
        '400':
          description: Invalid input
      requestBody:
        description: Update an existent distribution
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/distribution.yaml#/DistributionUpsertRequest'
      security:
        - cloudresource_auth: [ ]

  /distributions/{id}:
    get:
      tags:
        - distributions
      summary: Create new distribution
      description: ''
      operationId: getDistribution
      parameters:
        - name: id
          in: path
          description: ID of cloudresource to update
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'schemas/distribution.yaml#/DistributionUpsert'
        '400':
          description: Invalid input
      security:
        - cloudresource_auth: [ ]

# components:
#   schemas:
#     DistributionUpsertRequest:
#       type: object
#       properties:
#         id:
#           type: string
#           format: uuid

#     DistributionUpsert:
#       allOf: # Combines the main `DistributionUpsertRequest` schema with `DistributionUpsert`-specific properties 
#         - $ref: '#/components/schemas/DistributionUpsertRequest'
#         - type: object
#           # all other properties specific to a `Dog`
#           properties:
#             id:
#               type: string
#               format: uuid




  # /mutation-api/cloud-cdn/distributions/{id}:
  #   put:
  #     tags:
  #       - distributions
  #     summary: Update a distribution
  #     description: ''
  #     operationId: updateDistribution
  #     parameters:
  #       - name: id
  #         in: path
  #         description: ID of Cdn distribution that needs to be updated
  #         required: true
  #         schema:
  #           type: string
  #           format: uuid
  #     responses:
  #       '200':
  #         description: successful operation
  #         content:
  #           application/json:
  #             schema:
  #               $ref: 'schemas/distribution.yaml#/components/schemas/DistributionUpsert'
  #       '400':
  #         description: Invalid input
  #     requestBody:
  #       $ref: 'schemas/distribution.yaml#/components/schemas/DistributionUpsertRequest'
  #     security:
  #       - cloudresource_auth: [ ]
  #   delete:
  #     tags:
  #       - pet
  #     summary: Deletes a pet
  #     description: ''
  #     operationId: deletePet
  #     parameters:
  #       - name: api_key
  #         in: header
  #         description: ''
  #         required: false
  #         schema:
  #           type: string
  #       - name: id
  #         in: path
  #         description: Pet id to delete
  #         required: true
  #         schema:
  #           type: string
  #           format: uuid
  #     responses:
  #       '400':
  #         description: Invalid pet value
  #     security:
  #       - petstore_auth:
  #           - 'write:pets'
  #           - 'read:pets'
